version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mediago-postgres
    environment:
      POSTGRES_USER: mediago
      POSTGRES_PASSWORD: mediago@1551
      POSTGRES_DB: mediago_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mediago-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    container_name: mediago-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentic/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAKFA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # services

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8002:8002"
    depends_on:
      - postgres

  content-service:
    build: ./content-service
    container_name: content-service
    ports:
      - "8003:8003"
    depends_on:
      - mongodb

  video-uploader-service:
    build: ./video-uploader-service
    container_name: video-uploader
    ports:
      - "8004:8004"
    depends_on:
      - mongodb
      - postgres

  video-streaming-service:
    build: ./video-streaming-service
    container_name: video-streaming
    ports:
      - "8005:8005"
    depends_on:
      - postgres

  playlist-service:
    build: ./playlist-service
    container_name: playlist-service
    ports:
      - "8006:8006"
    depends_on:
      - postgres

  subscription-service:
    build: ./subscription-service
    container_name: subscription-service
    ports:
      - "8007:8007"
    depends_on:
      - postgres

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8008:8008"
    depends_on:
      - postgres

volumes:
  pgdata:
  mongodata: